version: '3.11'

#  If you have multiple environments, you may want to look at using a
#  docker-compose.override.yml configuration file. With this approach,
#  you'd add your base config to a docker-compose.yml file and then
#  use a docker-compose.override.yml file to override those config
#  settings based on the environment.

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn configuration.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: